
// export const homestoreProducts=[
//     {
//     id:1,
//     title: "Drummer",
//     img: "img/product-1.jpg",
//     price:10,
//     Company:"ARTIFY",
//     info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
//     inCart:false,
//     count:0,
//     total:0,   
// },

// {
//     id :2,
//     title: "Guitarist",
//     img: "img/product-2.jpg",
//     price:16,
//     Company:"ARTIFY",
//     info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
//     inCart:false,
//     count:0,
//     total:0,
// },
// {
//     id :3,
//     title: "Palm Wine Tapper",
//     img: "img/product-3.jpg",
//     price:25,
//     Company:"ARTIFY",
//     info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
//     inCart:false,
//     count:0,
//     total:0,
// },
// {
//     id :4,
//     title: "Mood",
//     img: "img/product-4.jpg",
//     price:12,
//     Company:"ARTIFY",
//     info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
//     inCart:false,
//     count:0,
//     total:0,
// },]

export const storeProducts=[
    {
    id:1,
    title: "Sorghum",
    img: "img/product-1.png",
    price:1000,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,   
},

{
    id :2,
    title: "Millet",
    img: "img/product-2.png",
    price:500,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :3,
    title: "Yam Tubers",
    img: "img/product-3.png",
    price:600,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :4,
    title: "Yam Flour(Elubo)",
    img: "img/product-4.png",
    price:600,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :5,
    title: "Cashew Nut",
    img: "img/product-5.png",
    price:1500,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :6,
    title: "Honey",
    img: "img/product-6.png",
    price:3000,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :7,
    title: "Palm Oil",
    img: "img/product-7.png",
    price:700,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :8,
    title: "Red Potatoes",
    img: "img/product-8.png",
    price:1800,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :9,
    title: "Vegetables",
    img: "img/product-9.png",
    price:500,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :10,
    title: "Wheat",
    img: "img/product-10.png",
    price:800,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :11,
    title: "Kolanut",
    img: "img/product-11.png",
    price:1200,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :12,
    title: "Rice Flour",
    img: "img/product-12.png",
    price:800,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :13,
    title: "Garri",
    img: "img/product-13.png",
    price:750,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :14,
    title: "Soy Beans",
    img: "img/product-14.png",
    price:600,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :15,
    title: "-----",
    img: "img/product-15.png",
    price:360,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :16,
    title: "Potatoes",
    img: "img/product-16.png",
    price:1450,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :17,
    title: "Chicken Feets",
    img: "img/product-17.png",
    price:2500,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :18,
    title: "Melon (Egusi)",
    img: "img/product-18.png",
    price:1600,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :19,
    title: "Bananas",
    img: "img/product-19.png",
    price:450,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :20,
    title: "Ginger",
    img: "img/product-20.png",
    price:1200,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :21,
    title: "Moringer Seeds",
    img: "img/product-21.png",
    price:2100,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :22,
    title: "Chicken Wings",
    img: "img/product-22.png",
    price:1850,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :23,
    title: "Smoked Fish",
    img: "img/product-23.png",
    price:1400,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :24,
    title: "Biter Kola",
    img: "img/product-24.png",
    price:1500,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :25,
    title: "Cocoyam",
    img: "img/product-25.png",
    price:1460,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :26,
    title: "Plantain",
    img: "img/product-26.png",
    price:750,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :27,
    title: "Ofada Rice",
    img: "img/product-27.png",
    price:1800,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :28,
    title: "Maize",
    img: "img/product-28.png",
    price:450,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :29,
    title: "Ugwu",
    img: "img/product-29.png",
    price:1250,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :30,
    title: "Cassava",
    img: "img/product-30.png",
    price:1400,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :31,
    title: "GrondNut",
    img: "img/product-17.png",
    price:1000,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :32,
    title: "Frozen Chicken",
    img: "img/product-32.png",
    price:1400,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :33,
    title: "Onions",
    img: "img/product-33.png",
    price:850,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :34,
    title: "Tiger Nut",
    img: "img/product-34.png",
    price:500,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :35,
    title: "Galic",
    img: "img/product-35.png",
    price:750,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :36,
    title: "Cocoa",
    img: "img/product-36.png",
    price:3500,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :37,
    title: "snail",
    img: "img/product-37.png",
    price:450,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :38,
    title: "Galic",
    img: "img/product-38.png",
    price:750,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :39,
    title:"Chicken Laps",
    img: "img/product-39.png",
    price:1800,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},]

export const detailsProduct ={
     id :1,
    title: "Millet",
    img: "img/product-2.png",
    price:42,
    company:"ADDAY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0, 
   }
